config/routes.rb
Rails.application.routes.draw do
  get 'about/index'      # http://localhost:3000/about/index
  get 'home/index'       # http://localhost:3000/home/index
  get 'dashboard/index'  # http://localhost:3000/dashboard/index
  root "home#index"      # http://localhost:3000/dashboard   

  devise_for :users
  resources :dashboard
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/about_controller.rb
class AboutController < ApplicationController
  def index
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception # Prevent CSRF attacks by raising an exception. # For APIs, you may want to use :null_session instead.
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  before_filter :authenticate_user! # devise check user for signed in
  def index    
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/about/index.html.erb
<div class="container">
  <h1>About#index</h1>
  <p>Find me in app/views/about/index.html.erb</p>
</div>

app/views/dashboard/index.html.erb
<div class="container">
  <h1>Welcome to your dashboard</h1>
</div>

app/views/home/index.html.erb
<!-- <h1>Home#index</h1> 
<p>Find me in app/views/home/index.html.erb</p> 
http://localhost:3000/home/index
-->

<div class="container">
  <h1>Welcome to our Site</h1>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <!-- < % = render 'partials/test' % > -->
  <%= render 'partials/head' %>
<body>
  <%= render 'partials/user_nav' %>  <!-- sign out, sign-in and sign-up -->

<%= yield %>

  <% if user_signed_in? %> 
    <%= render 'partials/jumbotron' %>
    <%= render 'partials/headings' %>

  <% else %> <!-- signin -->
    <%= render 'partials/navbar' %> <!-- < % = render 'partials/yield' % >   < % = yield % > -->
  <% end %>
  

</body>
  <%= render 'partials/footer' %>

</html>

app/views/partials/_footer.html.erb
<div class="container">
  <footer>
    <p>&copy; Company 2015</p>
  </footer>
</div>

app/views/partials/_head.html.erb
<head>
  <title>Devise Bootstrap Combo</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>

app/views/partials/_headings.html.erb
<!-- Example row of columns -->
<div class="container">
  <div class="row">
    <div class="col-md-4">
      <h2>Heading</h2>
      <p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui. </p>
      <p><a class="btn btn-default" href="#" role="button">View details &raquo;</a></p>
    </div>
    <div class="col-md-4">
      <h2>Heading</h2>
      <p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui. </p>
      <p><a class="btn btn-default" href="#" role="button">View details &raquo;</a></p>
   </div>
    <div class="col-md-4">
      <h2>Heading</h2>
      <p>Donec sed odio dui. Cras justo odio, dapibus ac facilisis in, egestas eget quam. Vestibulum id ligula porta felis euismod semper. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus.</p>
      <p><a class="btn btn-default" href="#" role="button">View details &raquo;</a></p>
    </div>
  </div>
</div>

app/views/partials/_jumbotron.html.erb
<!-- Main jumbotron for a primary marketing message or call to action -->
<div class="jumbotron">
  <div class="container">
    <h1>Hello, world!</h1>
    <p>This is a template for a simple marketing or informational website. It includes a large callout called a jumbotron and three supporting pieces of content. Use it as a starting point to create something more unique.</p>
    <p><a class="btn btn-primary btn-lg" href="#" role="button">Learn more &raquo;</a></p>
  </div>
</div>

<!-- <div class="container"> -->
  <!-- Example row of columns -->
  <!-- <div class="row">
    <div class="col-md-4">
      <h2>Heading</h2>
      <p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui. </p>
      <p><a class="btn btn-default" href="#" role="button">View details &raquo;</a></p>
    </div>
    <div class="col-md-4">
      <h2>Heading</h2>
      <p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui. </p>
      <p><a class="btn btn-default" href="#" role="button">View details &raquo;</a></p>
   </div>
    <div class="col-md-4">
      <h2>Heading</h2>
      <p>Donec sed odio dui. Cras justo odio, dapibus ac facilisis in, egestas eget quam. Vestibulum id ligula porta felis euismod semper. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus.</p>
      <p><a class="btn btn-default" href="#" role="button">View details &raquo;</a></p>
    </div>
  </div> -->
  <hr>
<!-- </div> /container -->

app/views/partials/_navbar.html.erb
<div class="container">
  <nav class="navbar navbar-inverse navbar-fixed-top"><!-- <div id="user_nav"> -->
    <div class="container">
      <%= yield %>

      <% if user_signed_in? %>
        <a class="btn btn-xs btn-default"> Signed in as <%= current_user.email %>. Not you? </a>
        <%= link_to "Sign Out", destroy_user_session_path, :method => :delete, :class => "btn btn-default btn-xs" %>
      <% else %>
        <%= link_to "Sign Up", new_user_registration_path, :class => "btn btn-default btn-xs" %>
        <%= link_to "Sign In", new_user_session_path, :class => "btn btn-default btn-xs" %>
        <!-- < % = render 'partials/yield' % > -->
      <% end %>
    
      <div class="container">
        <% flash.each do |name, msg| %>
          <%= content_tag :div, msg, :id => "flash_#{name}", :class => "btn btn-xs btn-default" %>
        <% end %>
      </div>

    </div>
  </nav>
</div>

app/views/partials/_test.html.erb
  <div class="container-narrow">
  <div class="masthead">
    <%= render 'partials/user_header' %>
    <h3 class="muted"><%= link_to "SimpleDevise", root_path %></h3>
    <h5 class="muted">A demo of using SimpleDB with Devise</h5>
  </div>
  <hr />
  <%= yield %>
</div>

app/views/partials/_user_header.html.erb
<!-- <ul class="nav nav-pills pull-right"> -->
<ul class="nav nav-pills">
  <% if user_signed_in? %>
    <li><%= link_to "Sign Out", destroy_user_session_path, :method => :delete, :class => "btn btn-default" %> %></li>
  <% else %>
    <li><%= link_to "Sign In", new_user_session_path, :method => :delete, :class => "btn btn-default btn-xs" %> %></li>
    <li><%= link_to "Sign Up", new_user_registration_path, :method => :delete, :class => "btn btn-default btn-xs" %> %></li>
  <% end %>
</ul>

app/views/partials/_user_nav.html.erb
<div class="container">
  <div id="user_nav">

    <%= link_to "home", home_index_path, :class => "btn btn-default btn-xs" %>
    <%= link_to "about", about_index_path, :class => "btn btn-default btn-xs" %>
    <%= link_to "dashboard", dashboard_index_path, :class => "btn btn-default btn-xs" %>
  
    <% if user_signed_in? %>
      <a class="btn btn-xs btn-default"> Signed in as <%= current_user.email %>. Not you? </a>
      <%= link_to "Sign Out", destroy_user_session_path, :method => :delete, :class => "btn btn-xs btn-default" %>
    <% else %>
      <%= link_to "Sign Up", new_user_registration_path, :class => "btn btn-default" %>
      <%= link_to "Sign In", new_user_session_path, :class => "btn btn-default" %>
      <!-- < % = render 'partials/yield' % > -->
    <% end %>
    
  </div>
    <% flash.each do |name, msg| %>
      <%= content_tag :div, msg, :id => "flash_#{name}", :class => "btn btn-xs btn-default" %>
    <% end %>
</div>

app/views/partials/_yield.html.erb
 <%= yield %>